spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lft_db?options=-c%20timezone=UTC
    username: quant
    password: quantpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ml:
  api:
    url: http://localhost:8000/predict